diabetes/website/models.py
from .import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    

class Prediction(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    prediction = db.Column(db.String(10))
    probability = db.Column(db.Float)
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

diabetes/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

diabetes/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db  # means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

diabetes/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, url_for, redirect
from flask_login import login_required, current_user




views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def welcome():
    if current_user.is_authenticated:
        if request.path == url_for('views.home'):
            # user is already on the home page, no need to redirect
            return render_template('home.html', user=current_user)
        else:
            # redirect to home page
            return redirect(url_for('views.home'))
    else:
        return render_template('welcome.html')

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
   
#returns home 
    return render_template("home.html", user=current_user)

diabetes/website/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" href="/static/main.css">

  <title>{% block title %}Home{% endblock %}</title>
</head>

<body style="background-image: url('/website/static/diabetes-g214d84236_1920.jpg');">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary" >
    <div style="float: left;">
      <a class="navbar-brand" href="/">
        <img src="/static/diabetes-g214d84236_1920.jpg" alt="Diabetes Detection System" height="50">
      </a>
    </div>
    <button class="navbar-toggler"  type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar"  style="float: right;">
      <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" id="home" href="/">Home</a>
        <a class="nav-item nav-link" id="results" href="/results">Results</a>
        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>

        {% else %}
        <a class="nav-item nav-link" id="login" href="/login">Login</a>
        <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
        {% endif %}
      </div>
    </div>
  </nav>

  {% with messages = get_flashed_messages(with_categories=true) %} {% if
  messages %} {% for category, message in messages %} {% if category ==
  'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %} {% endfor %} {% endif %} {% endwith %}

  <div class="container">{% block content %} {% endblock %}</div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block javascript %}
  <script type="text/javascript">
    function deleteNote(noteId) {
      fetch("/delete-note", {
        method: "POST",
        body: JSON.stringify({ noteId: noteId }),
      }).then((_res) => {
        window.location.href = "/";
      });
    }
  </script>
  {% endblock %}
</body>

</html>

diabetes/website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content %}

<div class="section no-pad-bot" id="index-banner">
    <div class="container">
     <!-- <h5 style="text-align: center; color: brown; font-weight: 600;">{{dect}}</h5> -->
     <h5 style="text-align: center; color: brown; font-weight: 600;">{{pred}}</h5>
      <h1 style="margin-left: 35%; color: aqua; font-weight: bold;" >Diabetes Detection Portal</h1><br>

      <!-- <div class="row center">
        <h5 align=" center" style="color: aqua; margin-left: 35%;">Detect the Presences of having Diabetes
        <br>
        </h5>
      </div> -->


      <div class="row">
        <form action='/predict' method="post" class="col s12">
            <div class="row" align="center" style="margin-top: 10%;">
              <div class="input-field col s4">
                <label for="first_name"><b>Gravidity</b></label>
                <br>
                <input placeholder="No. of Pregnancies" name="1" id="first_name" type="text" class="validate">
            </div>
                <div class="input-field col s4">
                    <label for="last_name"><b>Glucose(mg/dL) </b></label>
                    <br>
                    <input id="last_name" name="2" placeholder="Glucose level in sugar"  type="text" class="validate" style="margin-left: 5%;"> <br>
    
                </div>
    
                <div class="input-field col s4">
                    <label for="_name"><b>Blood Pressure</b></label>
                    <br>
                    <input id="_name" name="3" placeholder="BloodPressure" type="text" class="validate"><br>
    
                </div>
                <div class="input-field col s4">
                    <label for="first_name"><b>Skin Turgor</b></label>
                    <br>
                    <input placeholder="SkinThickness" name="4" id="first_name" type="text" class="validate"><br>
                </div>
                <div class="input-field col s4" style="padding-top: 20px; color: rgb(2, 55, 55);">
                    <label for="last_name"><b>Insulin</b></label>
                    <br>
                    <input id="last_name" name="5" placeholder="Insulin level"  type="text" class="validate"><br>
                </div>
                <div class="input-field col s4" style="padding-top: 20px; color: rgb(2, 55, 55);">
                  <label ><b>BMI</b></label>
                  <br>
                  <input name = '6' placeholder="Body Mass Index" style="margin-left: 1%;"><br>

                </div>
                <div class="input-field col s4" style="padding-top: 20px; color: rgb(2, 55, 55);">
                  <label for="last_name"><b>DiabetesPedigreeFunction</b></label>
                  <br>
                  <input id="last_name" name="7" placeholder="DiabetesPedigreeFunction"  type="text" class="validate">
              </div>
                <div class="input-field col s4" style="padding-top: 20px; color: rgb(2, 55, 55);">
                    <label for="_name"><b>Age</b></label>
                    <br>
                    <input id="_name" name="8" placeholder="Age" type="text" class="validate"><br><br>
                </div>
                
          </div>
    
          <div class="row center">
    
            <button type="submit" class="btn-large waves-effect waves-light orange" style="margin-left: 40%; margin-top: 5%; color: rgb(133, 133, 230);">Detect Probability</button>

          </div>
        </form>
  </div>
 
{% endblock %}
    

diabetes/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

diabetes/website/templates/results.html
{% extends 'base.html' %}

{% block title %}
    Results
{% endblock %}

{% block content %}
    <h1 style="margin-left: 45%; font-weight: bold;">Results</h1>
    {% if pred %}
        <p style="padding-top: 50px; margin-left: 45%; font-weight: bold;">{{ pred }}</p>
    </div>
    {% else %}
        <p style="padding-top: 50px; margin-left: 45%; font-weight: bold;">No prediction was made.</p>
    {% endif %}
{% endblock %}

diabetes/website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

diabetes/website/templates/welcome.html
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('views.home') }}">My App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a>
          {% else %}
            <a class="nav-link" href="{{ url_for('auth.login') }}">Log in</a>
            <a class="nav-link" href="{{ url_for('auth.sign_up') }}">Sign up</a>
          {% endif %}
        </ul>
      </div>
    </nav> -->
<style>
    body{
        background-color: rgb(169, 155, 144);
    }
</style>
    {% if current_user.is_authenticated %}
      <h1>Welcome {{ current_user.first_name }}!</h1>
      <p>You are logged in. Click <a href="{{ url_for('auth.logout') }}">here</a> to log out.</p>
      <p>Click <a href="{{ url_for('views.home') }}">here</a> to go to the home page.</p>
    {% else %}
      <h1 align="center">Welcome To Diabetes detection system!</h1>
      <p align="center">Please <a href="{{ url_for('auth.login') }}">log in</a> or <a href="{{ url_for('auth.sign_up') }}">sign up</a> to continue.</p>
    {% endif %}

  